backend:
  name: "git-gateway"

media_folder: "src/images/uploads"
public_folder: "/images/uploads"

collections:
  - label: "Pos"
    name: "pos"
    folder: "src/pos"
    create: true
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post.njk"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown", buttons: ["bold", "italic", "code", "link", "heading-two", "heading-three", "heading-four", "heading-five", "heading-six", "quote", "bulleted-list", "numbered-list"]}
